# Example: StatefulSet with NFS storage
# Each pod gets its own persistent volume

---
apiVersion: v1
kind: Service
metadata:
  name: web-headless
spec:
  clusterIP: None
  selector:
    app: web
  ports:
  - port: 80
    name: web

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "web-headless"
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
        command:
          - sh
          - -c
          - |
            hostname > /usr/share/nginx/html/index.html
            echo "Pod: $(hostname)" >> /usr/share/nginx/html/index.html
            echo "Time: $(date)" >> /usr/share/nginx/html/index.html
            nginx -g 'daemon off;'
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 1Gi

